### ISSUE TITLE
Problem serializing nullable member

### ISSUE THREAD

**Issue by Dini001** [esskar/Serialize.Linq#81] opened 2017-08-16 18:01 UTC
ToBooleanExpression() is not able to recreate de Expression when using a nullable member of a class

`var pc1 = new PropertyContainer();
pc1.Property1 = null;    //Nullable with null value`

Work when is local property
`Guid? property1 = pc1.Property1;
Expression<Func<Guid, bool>> fonction1 = x => property1 != null && x != property1;
var ExpressionNode1 = fonction1.ToExpressionNode();
ExpressionNode1.ToBooleanExpression<Guid>();`

Doesn't work when nullable member of a class is null
`Expression<Func<Guid, bool>> fonction2 = x => pc1.Property1 != null && x != pc1.Property1;
var ExpressionNode2 = fonction2.ToExpressionNode();
ExpressionNode2.ToBooleanExpression<Guid>(); //===> Exception`

Doesn't work when nullable member of a class is checked for null
`pc1.Property1 = Guid.NewGuid();    //Nullable with null value
Expression<Func<Guid, bool>> fonction3 = x => pc1.Property1 != null;
var ExpressionNode3 = fonction3.ToExpressionNode();
ExpressionNode3.ToBooleanExpression<Guid>(); //===> Exception`

**Comment by esskar** [comment] 2017-08-17 15:53
thanks. i will have a look at it asap

**Comment by esskar** [comment] 2017-08-18 08:23
the issue is fixed with the last checkin; will publish a new version later the day.

**Comment by esskar** [comment] 2017-08-20 13:51
New version is published
https://www.nuget.org/packages/Serialize.Linq/1.3.1.1

**Closed by esskar** 2017-08-20 13:51 UTC
